#!/bin/sh
# original copied from ipfs/go-ipfs@sha256:d345563bc64544b03a0a4f16b1b98a1b52f31377af4c6c76b334c90f4ac6836b:/usr/local/bin/start_ipfs
set -e
user=ipfs
repo="$IPFS_PATH"

if [ `id -u` -eq 0 ]; then
  echo "Changing user to $user"
  # ensure folder is writable
  su-exec "$user" test -w "$repo" || chown -R -- "$user" "$repo"
  # restart script with new privileges
  exec su-exec "$user" "$0" "$@"
fi

# 2nd invocation with regular user
ipfs version

if [ -e "$repo/config" ]; then
  echo "Found IPFS fs-repo at $repo"
else
  # overriding profile to always be server
  ipfs init --profile server

  ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
  ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080

  # some extra config changes here
  ipfs config --json Bootstrap '[]'
  ipfs config --json Datastore.BloomFilterSize 1048576
fi

exec ipfs "$@"
